const fixaConstants = {
  TOAST: {
    MESSAGES: {
      ERROR: {
        invalidCredentials: 'user not exist',
      },
      SUCCESS: {
        cwsSuccess: 'Web Service Created Successfully',
        addedIssue: 'issue added Successfully',
        SignIn: 'Sign In Successfully',
        signUp: 'Sign Up Successfully',
        logoutSuccess: 'Logout Successfully',
        signInSuccess: 'Sign in successfully',
      },
    },
  },
  LABEL: {
    UPDATE_LABEL: 'Update',
    ADD_LABEL: 'Add',
    TITLE: 'Title',
    DESCRIPTION: 'Description',
    LABELS: 'Labels',
    NEW_LABEL: 'New Label',
    LABEL_NAME: 'Label Name',
    STATUS: 'Status',
    TOTAL_DUR: 'Total duration',
    ARTIFACTS: 'Artifacts',
    CREDENTIALS_TYPE: 'Credentials Type',
    NAME: 'Name',
    PROJECT_ID: 'Project ID',
  },
  // POCKETSTUDIO: {
  //   POCKET_STUDIO: 'POCKET STUDIO AI',
  // },
  BUTTON_TEXT: {
    EDIT: 'Edit',
    VERIFY: 'Verify',
    RENEW: ' Renew',
    CONNECT: 'Connect',
    UPDATE: 'Update',
    DOWNLOAD: 'Download',
    REPOSITORY: 'Repository',
    CANCEL: 'Cancel',
    SAVE: 'Save',
    NEXT: 'Next',
    PUBLIC: 'Public',
    PRIVATE: 'Private',
    BACK: 'Back',
    ADD: 'Add',
    SAVE_CHNG: 'Save Changes',
    UPDATES: 'Updates',
    NEW_LABEL: 'New Label',
    SAVE_CHANGES: 'Save Changes',
    ACTIVE: 'Active',
    PREVIOUS: 'Previous',
    COMING_SOON: 'Coming Soon',
  },
  SIGNIN: {
    WELCOMETEXT: `Welcome to Voyra Events `,
    SIGNINBUTTONTEXT: 'Click here to Sign In',
    LEARNMORE: 'Learn more about Voyra Events on',
    // DOMAIN: 'https://PocketStudio.ai/',
  },
  AUTH: {
    PASSWORD_REGEX: /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[^\w\s]).{8,}$/,
    PASSWORD_ERROR:
      'Password must be 8+ chars with uppercase, lowercase, number, and special character',
    PASSWORD_REQUIRED_ERROR: 'Password is required',
    FORGOT_PASSWORD: 'Forgot Password?',
    RESET_PASSWORD: 'Reset Password',
    NEW_PASSWORD_REQUIRED_ERROR: 'New Password is required',
    OLD_PASSWORD_REQUIRED_ERROR: 'Old Password is required',
    CONFIRM_PASSWORD: 'Confirm Password',
    CONFIRM_PASSWORD_ERROR: 'Passwords do not match',
    EMAIL_REQUIRED_ERROR: 'Email is required',
    EMAIL_ERROR: 'Invalid email',
    EMAIL_REGEX:
      /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
    OTP_RESEND_TIMER: 180,
    FORGOT_PASSWORD_TEXT:
      "Enter your email, and we'll send you a reset token to set a new password",
    PLEASE_WAIT_TEXT: 'Please wait as we verify your details.',
    DO_NOT_NAVIGATE_TEXT: 'Do not refresh or leave this page',
    OTP_EXPIRY_TIMER: 900,
    SIGN_IN_TEXT: 'Enter your email and password to sign in!',
    SIGN_UP_TEXT: 'Enter your email and password to sign up!',
    FIRST_NAME_REQUIRED_ERROR: 'First name is required',
    LAST_NAME_REQUIRED_ERROR: 'Last name is required',
    CONFIRM_PASSWORD_REQUIRED_ERROR: 'Confirm Password is required',
    ACCEPT_TERMS_TEXT: 'You must agree to the Terms and Privacy Policy',
    CRYPTO_KEY: process.env.REACT_APP_CRYPTO_KEY,
  },
  HEY: 'Hey,',
  NO_DATA_AVAIL: 'No Data Available',
  TABS: {
    DETAILS: 'Details',
  },
  TABLE_HEADER: {
    SR_NO: 'S.NO',
    ISSUES: 'ISSUES',
    AUTHOR: 'AUTHOR',
    PR_STATUS: 'PR STATUS',
    ACTION: 'ACTION',
    BRANCH_NAME: 'BRANCH NAME',
    OPEN: 'OPEN',
    CLOSED: 'CLOSED',
  },
  NO_DATA: 'No Data Available',
}

export default fixaConstants
